/*
 * Turns symbols from a captured icon sprite into React components.
 *
 * The live site draws its icons from one 348-symbol sprite and references them
 * with `<use xlink:href="#icon_...">`. Copying the glyphs we actually use keeps
 * them exact — a redrawn approximation is the kind of difference nobody can
 * name but everybody sees — without carrying 434 KB of sprite we do not need.
 *
 *   node scripts/extract-icons.mjs <sprite.svg> <out.tsx> <id> [<id> ...]
 */
import { readFileSync, writeFileSync } from "node:fs";

const [, , spritePath, outPath, ...ids] = process.argv;
const sprite = readFileSync(spritePath, "utf8");

/** `icon_layout_withdraw-circle` -> `WithdrawCircleIcon` */
function componentName(id) {
  const tail = id.replace(/^icon_[a-z]+_/, "");
  return (
    tail
      .split(/[-_]/)
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join("") + "Icon"
  );
}

/** SVG attribute names React spells differently. */
const REACT_ATTRS = {
  "fill-rule": "fillRule",
  "clip-rule": "clipRule",
  "stroke-width": "strokeWidth",
  "stroke-linecap": "strokeLinecap",
  "stroke-linejoin": "strokeLinejoin",
  "stroke-dasharray": "strokeDasharray",
  "fill-opacity": "fillOpacity",
  "stroke-opacity": "strokeOpacity",
  "stop-color": "stopColor",
  "stop-opacity": "stopOpacity",
  "xlink:href": "xlinkHref",
};

function toJsx(markup) {
  let out = markup;
  for (const [from, to] of Object.entries(REACT_ATTRS)) {
    out = out.replaceAll(` ${from}=`, ` ${to}=`);
  }
  // Self-close the void-ish shapes that the sprite writes as pairs.
  return out.replace(/<(path|rect|circle|ellipse|line|polygon|polyline|use|stop)([^>]*)><\/\1>/g, "<$1$2 />");
}

const parts = [
  "/**",
  " * Icons taken verbatim from the live site's sprite.",
  " *",
  " * Generated by scripts/extract-icons.mjs — edit that, or re-run it against a",
  " * fresh capture, rather than editing the paths here. Each one inherits its",
  " * colour from `currentColor`, which is how the sprite draws them.",
  " */",
  "",
];

for (const id of ids) {
  const match = sprite.match(new RegExp(`<symbol[^>]*id="${id}"[^>]*>([\\s\\S]*?)</symbol>`));
  if (!match) {
    console.error(`missing: ${id}`);
    continue;
  }
  const head = sprite.match(new RegExp(`<symbol[^>]*id="${id}"[^>]*>`))[0];
  const viewBox = (head.match(/viewBox="([^"]+)"/) || [, "0 0 16 16"])[1];
  const body = toJsx(match[1].replace(/\s+/g, " ").trim());

  parts.push(
    `export function ${componentName(id)}(props: React.SVGProps<SVGSVGElement>) {`,
    `  return (`,
    `    <svg viewBox="${viewBox}" width="16" height="16" aria-hidden {...props}>`,
    `      ${body}`,
    `    </svg>`,
    `  );`,
    `}`,
    "",
  );
}

writeFileSync(outPath, parts.join("\n"));
console.log(`${ids.length} icons -> ${outPath}`);
